#########################################################
#
#   DEVICE_TRACKERS
#
#########################################################

#----  iCloud iPhone Location Services ------------------------
- platform: icloud3
  username: !secret icloud_username
  password: !secret icloud_password
  account_name: gary_icloud
  unit_of_measurement: mi
  gps_accuracy_threshold: 75
  include_device: 
    - gary_iphone
    - lillian_iphone
    
  #The following are examples of device inclusion/exclusion:
  #include_device_type: iphone
  #include_device_types: 
  #  - iphone
  #exclude_devices: 
  #  - lillian_iphone
  #  - connies_ipad
  #exclude_device_types: ipad

