#########################################################
#
#   BADGE TEMPLATE SENSORS
#
#########################################################
- platform: template
  sensors:
  
  
#--- Gary location badge --------------------
    gary_iphone_badge:  
      friendly_name: Gary
      value_template: ''
      entity_picture_template: /local/gary.png
      
#--- Garage Door Open/Closed --------------------
    garage_door_badge:
      value_template: >-
        {{states.sensor.garage_door.state}} 
      entity_picture_template: >-
        {% if states.sensor.garage_door.state == "Closed" %}
          /local/garage-door-closed.png
        {% else %}
          /local/garage-door-open.png 
        {% endif %}
              
#--- Hot Water Heater On/Off  --------------------
- platform: template
  sensors:
    hot_water_heater_badge:
      value_template: >-
        {{states.sensor.hot_water_heater_temp.state}} °F
      entity_picture_template: >-
        {% if states.switch.hot_water_heater.state == "on" %}
          /local/hot-water-heater-on.png
        {% else %}
          /local/hot-water-heater-off.png
        {% endif %}
              
