#########################################################
#
#   BADGE TEMPLATE SENSORS
#
#########################################################
- platform: template
  sensors:
    #--- Gary/Lillian location badge --------------------
    gary_badge:
      value_template: >-
        {% if states("device_tracker.gary_iphone") %}
          {% if states("device_tracker.gary_iphone") != "not_home" %}
            {{ states("device_tracker.gary_iphone") | title }}
          {% elif state_attr("device_tracker.gary_iphone","distance") %}
            {{ state_attr("device_tracker.gary_iphone","distance") }} mi
          {% else %}
            Waiting
          {% endif %} 
        {% endif %}            
      entity_picture_template: /local/gary.png

    lillian_badge:
      value_template: >-
        {% if states("device_tracker.lillian_iphone") %}
          {% if states("device_tracker.lillian_iphone") != "not_home" %}
            {{ states("device_tracker.lillian_iphone") | title }}
          {% elif state_attr("device_tracker.lillian_iphone","distance") %}
            {{ state_attr("device_tracker.lillian_iphone","distance") }} mi
          {% else %}
            Waiting
          {% endif %}
        {% endif %}  
      entity_picture_template: /local/lillian.png

  #--- Garage Door Open/Closed --------------------
    garage_door_badge:
      value_template: >-
        {{states.sensor.garage_door.state}} 
      entity_picture_template: >-
        {% if states.sensor.garage_door.state == "Closed" %}
          /local/garage-door-closed.png
        {% else %}
          /local/garage-door-open.png 
        {% endif %}
              
#--- Hot Water Heater On/Off  --------------------
- platform: template
  sensors:
    hot_water_heater_badge:
      value_template: >-
        {{states.sensor.hot_water_heater_temp.state}} °F
      entity_picture_template: >-
        {% if states.switch.hot_water_heater.state == "on" %}
          /local/hot-water-heater-on.png
        {% else %}
          /local/hot-water-heater-off.png
        {% endif %}
              

#---- Day of Week Templates --------------------
- platform: template
  sensors:
    day_of_week:
      value_template: >
        {{ now().strftime("%a") }}
      entity_id:
        - sensor.day_of_week
 
- platform: template
  sensors:
    day_date:
      value_template: >
        {{ now().strftime("%A, %b %d, %Y") }}
      entity_id:
        - sensor.day_date

