#########################################################
#
#   ICLOUD3 DEVICE_TRACKER ATTRIBUTE DISPLAY TEMPLATE SENSORS
#
#########################################################

#sensor:

#---- iPhone Device Tracker Attribute Templates ----- Gary ---------------
- platform: template
  sensors:
    garyiphone_distance:
      value_template: '{{float(state_attr("device_tracker.garyiphone","distance"))}}'
      unit_of_measurement: 'mi'
    garyiphone_calc_distance:
      value_template: '{{float(state_attr("device_tracker.garyiphone","calc_distance"))}}'
      unit_of_measurement: 'mi'
    garyiphone_waze_distance:
      value_template: '{{float(state_attr("device_tracker.garyiphone","waze_distance"))}}'
      unit_of_measurement: 'mi'
    garyiphone_travel_time:
      value_template: '{{state_attr("device_tracker.garyiphone","travel_time")}}'

    garyiphone_battery:
      value_template: '{{state_attr("device_tracker.garyiphone","battery")}}'
      unit_of_measurement: '%'
    garyiphone_dir_of_travel:
      value_template: '{{state_attr("device_tracker.garyiphone","dir_of_travel")}}'
    garyiphone_gps_accuracy:
      value_template: '{{state_attr("device_tracker.garyiphone","gps_accuracy")}}'
    garyiphone_poll_count:
      value_template: '{{state_attr("device_tracker.garyiphone","poll_count")}}'
    garyiphone_info:
      value_template: '{{state_attr("device_tracker.garyiphone","info")}}'
       
    garyiphone_interval:
      value_template: '{{state_attr("device_tracker.garyiphone","interval")}}'
    garyiphone_last_located:
      value_template: '{{state_attr("device_tracker.garyiphone","last_located")}}'
    garyiphone_last_update:
      value_template: '{{state_attr("device_tracker.garyiphone","last_update")}}'
    garyiphone_next_update:
      value_template: '{{state_attr("device_tracker.garyiphone","next_update")}}' 
