#########################################################
#
#   IPHONE/ICLOUD SELECTION AUTOMATIONS
#
#########################################################
- alias: set_gary_iphone_interval
  trigger:
    - platform: state
      entity_id: input_select.icloud_set_interval
  action:
    - service: device_tracker.icloud_set_interval
      data_template:
        account_name: gary_icloud
        device_name: gary_iphone
        interval: "{{ states.input_select.icloud_set_interval.state }}"

- alias: icloud_command
  trigger:
    - platform: state
      entity_id: input_select.icloud_commands
  action:
    - service: device_tracker.icloud_update
      data_template:
        account_name: gary_icloud
        command: "{{ states.input_select.icloud_commands.state }}"        

- alias: icloud_debug_command
  trigger:
    - platform: state
      entity_id: input_select.icloud_debug_commands
  action:
    - service: device_tracker.icloud_update
      data_template:
        account_name: gary_icloud
        command: "{{ states.input_select.icloud_debug_commands.state }}"