#########################################################
#
#   ATTRIBUTE DISPLAY TEMPLATE SENSORS
#
#########################################################

#---- iPhone Device Tracker Attribute Templates ----- Gary ---------------
- platform: template
  sensors:
    gary_iphone_distance:
      value_template: '{{float(state_attr("device_tracker.gary_iphone","distance"))}}'
      unit_of_measurement: 'mi'
    gary_iphone_calc_distance:
      value_template: '{{float(state_attr("device_tracker.gary_iphone","calc_distance"))}}'
      unit_of_measurement: 'mi'
    gary_iphone_waze_distance:
      value_template: '{{float(state_attr("device_tracker.gary_iphone","waze_distance"))}}'
      unit_of_measurement: 'mi'
    gary_iphone_travel_time:
      value_template: '{{state_attr("device_tracker.gary_iphone","travel_time")}}'

    gary_iphone_battery:
      value_template: '{{state_attr("device_tracker.gary_iphone","battery")}}'
      unit_of_measurement: '%'
    gary_iphone_dir_of_travel:
      value_template: '{{state_attr("device_tracker.gary_iphone","dir_of_travel") | replace("_"," ") | title}}'
    gary_iphone_gps_accuracy:
      value_template: '{{state_attr("device_tracker.gary_iphone","gps_accuracy")}}'
    gary_iphone_poll_count:
      value_template: '{{state_attr("device_tracker.gary_iphone","poll_count")}}'
    gary_iphone_info:
      value_template: '{{state_attr("device_tracker.gary_iphone","info")}}'
       
    gary_iphone_interval:
      value_template: '{{state_attr("device_tracker.gary_iphone","interval")}}'
    gary_iphone_last_located:
      value_template: '{{state_attr("device_tracker.gary_iphone","last_located")}}'
    gary_iphone_last_update:
      value_template: '{{state_attr("device_tracker.gary_iphone","last_update")}}'
    gary_iphone_next_update:
      value_template: '{{state_attr("device_tracker.gary_iphone","next_update")}}' 


#---- iPhone Device Tracker Attribute Templates ----- Lillian ------------
- platform: template
  sensors:
    lillian_iphone_distance:
      value_template: '{{float(state_attr("device_tracker.lillian_iphone","distance"))}}'
      unit_of_measurement: 'mi'
    lillian_iphone_calc_distance:
      value_template: '{{float(state_attr("device_tracker.lillian_iphone","calc_distance"))}}'
      unit_of_measurement: 'mi'
    lillian_iphone_waze_distance:
      value_template: '{{float(state_attr("device_tracker.lillian_iphone","waze_distance"))}}'
      unit_of_measurement: 'mi'
    lillian_iphone_travel_time:
      value_template: '{{float(state_attr("device_tracker.lillian_iphone","travel_time"))}}'

    lillian_iphone_battery:
      value_template: '{{float(state_attr("device_tracker.lillian_iphone","battery"))}}'
      unit_of_measurement: '%'
    lillian_iphone_dir_of_travel:
      value_template: '{{state_attr("device_tracker.lillian_iphone","dir_of_travel") | replace("_"," ") | title}}'
    lillian_iphone_gps_accuracy:
      value_template: '{{state_attr("device_tracker.lillian_iphone","gps_accuracy")}}'
    lillian_iphone_poll_count:
      value_template: '{{state_attr("device_tracker.lillian_iphone","poll_count")}}'
    lillian_iphone_info:
      value_template: '{{state_attr("device_tracker.lillian_iphone","info")}}'
 
    lillian_iphone_interval:
      value_template: '{{float(state_attr("device_tracker.lillian_iphone","interval"))}}'
    lillian_iphone_last_located:
      value_template: '{{state_attr("device_tracker.lillian_iphone","last_located")}}'
    lillian_iphone_last_update:
      value_template: '{{state_attr("device_tracker.lillian_iphone","last_update")}}'
    lillian_iphone_next_update:
      value_template: '{{state_attr("device_tracker.lillian_iphone","next_update")}}'

#---- iPhone Device Tracker Attribute Templates ----- Formatted -----------
- platform: template
  sensors:
    gary_iphone_formatted:
      value_template: '{{states("device_tracker.gary_iphone") | title}}'
    gary_smartthings_formatted:
      value_template: '{{states("sensor.gary_smartthings")| title}}'

    lillian_iphone_formatted:
      value_template: '{{states("device_tracker.lillian_iphone") | title}}'
    lillian_smartthings_formatted:
      value_template: '{{states("sensor.lillian_smartthings") | title}}'

    someone_home_flag_formatted:
      value_template: '{{states.sensor.someone_home_flag.state | title}}'
      
      