#########################################################
#
#   SENSORS
#
#   SMARTTHINGS PRESENCE MQTT SENSOR
#
#   Set 'Home' or 'Away' text for different device trackers
#
#########################################################

#   smartthings/Gary-iPhone/presence/state
- platform: mqtt
  name: 'gary_smartthings'
  state_topic: 'smartthings/Gary-iPhone/presence/state'
  value_template: '{% if value == "present" %}home{% else %}away{% endif %}'
  icon: mdi:map-marker-radius
  retain: true

#--------------------------------------------------------------
#   smartthings/Lillian-iPhone/presence/state  
- platform: mqtt
  name: 'lillian_smartthings'
  state_topic: 'smartthings/Lillian-iPhone/presence/state'
  value_template: '{% if value == "present" %}home{% else %}away{% endif %}'
  icon: mdi:map-marker-radius
  retain: true

#---- Set Someone Home Flag --------------------
- platform: template
  sensors:
    someone_home_flag:
      friendly_name: Someone Home Flag
      entity_id: 
        - device_tracker.gary
        - device_tracker.lillian
      value_template: >
        {% if states.device_tracker.gary_iphone.state == 'home' or states.device_tracker.lillian_iphone.state == 'home' %}
          home
        {% else %}
          all_away
        {% endif %}
      